server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

---

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /db
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    mybatis:
      mapper-locations:
        - classpath:mapper/**.xml
      configuration:
        map-underscore-to-camel-case: true

---
  spring:
    config:
      activate:
        on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/board
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          format_sql: true
      show-sql: true

      mybatis:
        mapper-locations:
          - classpath:mapper/**.xml
        configuration:
          map-underscore-to-camel-case: true







